var that=this;function __skpm_run(t,e){that.context=e;var r=function(t){var e={};function r(n){if(e[n])return e[n].exports;var u=e[n]={i:n,l:!1,exports:{}};return t[n].call(u.exports,u,u.exports,r),u.l=!0,u.exports}return r.m=t,r.c=e,r.d=function(t,e,n){r.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:n})},r.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},r.t=function(t,e){if(1&e&&(t=r(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var u in t)r.d(n,u,function(e){return t[e]}.bind(null,u));return n},r.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return r.d(e,"a",e),e},r.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},r.p="",r(r.s="./src/main.js")}({"./src/inputModal.js":
/*!***************************!*\
  !*** ./src/inputModal.js ***!
  \***************************/
/*! exports provided: default */function(t,e,r){"use strict";r.r(e),e.default=function(t,e,n,u){var i=r(/*! sketch/ui */"sketch/ui"),o=r(/*! sketch/settings */"sketch/settings"),a=!0,s=null,f=!0,c="Column amount",m=null,l=!0,h=!0,d="Gutter width",p=null,g=!0,y=o.settingForKey(n),b=o.settingForKey(u);if(m=y||12,p=b||12,i.getInputFromUser(t+" - Gutters on the outside?",{type:i.INPUT_TYPE.selection,possibleValues:["Yes","No"]},function(t,e){t?a=!1:s=e}),a){for(;f;)i.getInputFromUser(c,{initialValue:m},function(t,e){if(t)return l=!1,g=!1,void(f=!1);o.setSettingForKey(n,e),m=e,c="Column amount - is not a number"}),isNaN(m)||(f=!1),m<=0&&(c="Column amount - enter a number above 0",f=!0);if(l)for(;h;)if(i.getInputFromUser(d,{initialValue:p},function(t,e){if(t)return g=!1,void(h=!1);o.setSettingForKey(u,e),p=e,d="Gutter width - is not a number"}),isNaN(p)||(h=!1),p<=e){d=0==e?"Gutter width - enter a number above 0":"Gutter width - enter a positive number",h=!0}}return{outsideGutter:s,colAmount:m,gutterWidth:p,inputComplete:g}}},"./src/main.js":
/*!*********************!*\
  !*** ./src/main.js ***!
  \*********************/
/*! exports provided: gutters, columns */function(t,e,r){"use strict";r.r(e),r.d(e,"gutters",function(){return l}),r.d(e,"columns",function(){return h});var n=r(/*! sketch */"sketch"),u=r.n(n),i=r(/*! ./inputModal */"./src/inputModal.js"),o=u.a.getSelectedDocument().selectedLayers,a=o.length,s=r(/*! sketch/dom */"sketch/dom").Shape,f=r(/*! sketch/dom */"sketch/dom").Group,c=r(/*! sketch/ui */"sketch/ui"),m="Select a layer";function l(){if(0===a)return c.message(m);var t=Object(i.default)("GUTTERS",0,"gutterKey1","gutterKey2"),e=function(e,r){o.forEach(function(n){var u=parseInt(t.colAmount)+e,i=(n.frame.width-u*t.gutterWidth)/t.colAmount,o=function(e,r){return Math.trunc(n.frame.x+t.gutterWidth*e+i*(e+r))},a=t.gutterWidth*u;if(!(n.frame.width>a))return c.message("Gutters are too big for "+n.name);for(var m=new f({name:"Gutter",parent:n.parent}),l=0;l<u;l++)new s({name:"Gutter",parent:m,frame:{height:n.frame.height,width:t.gutterWidth,x:o(l,r),y:n.frame.y},style:{fills:["#ff0000"],opacity:.5,borders:[{thickness:0}]}});m.adjustToFit()})};"Yes"===t.outsideGutter&&t.inputComplete&&e(1,0),"No"===t.outsideGutter&&t.inputComplete&&e(-1,1)}function h(){if(0===a)return c.message(m);var t=Object(i.default)("COLUMNS",-1,"colKey1","colKey2");o.forEach(function(e){var r=[],n=function(n,u){for(var i=parseInt(t.colAmount)+n,o=t.gutterWidth*i,a=(e.frame.width-i*t.gutterWidth)/t.colAmount,s=function(r,n){return Math.trunc(e.frame.x+t.gutterWidth*r+a*(r+n))},f=0;f<i;f++)r.push(s(f,u));return o},u=function(n){var u=0,i=new f({name:"Columns",parent:e.parent});i.frame.x=e.frame.x,i.frame.y=e.frame.y,i.frame.width=e.frame.width,i.frame.height=e.frame.height;for(var o=0;o<r.length-1;o++){var a=r[o+1]-r[o]-Number(t.gutterWidth);u+=a;var c=t.gutterWidth*o+u-a+n,m=new s({name:"Column",parent:i,frame:{height:e.frame.height,x:c,width:a,y:0},style:{fills:["#00A2FF"],borders:[{thickness:0}]}});0==t.gutterWidth?m.style.opacity=o%2==0?.4:.5:m.style.opacity=.4}};if("Yes"===t.outsideGutter){if(!(e.frame.width>n(1,0)))return c.message("Gutters are too big for "+e.name);t.inputComplete&&u(Number(t.gutterWidth))}if("No"===t.outsideGutter){if(!(e.frame.width>n(-1,1)))return c.message("Gutters are too big for "+e.name);r.unshift(e.frame.x-t.gutterWidth),r.push(e.frame.x+e.frame.width),t.inputComplete&&u(0)}})}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(t,e){t.exports=require("sketch")},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/dom")},"sketch/settings":
/*!**********************************!*\
  !*** external "sketch/settings" ***!
  \**********************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/settings")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/ui")}});"default"===t&&"function"==typeof r?r(e):r[t](e)}that.gutters=__skpm_run.bind(this,"gutters"),that.onRun=__skpm_run.bind(this,"default"),that.columns=__skpm_run.bind(this,"columns");